-- Esquema objetivo para la persistencia multiusuario del módulo financiero.
-- Ejecutar como migración controlada después de validar nombres y permisos.

create table if not exists finance_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  numeric_value numeric,
  text_value text,
  effective_from date not null default current_date,
  updated_at timestamptz not null default now()
);

create table if not exists finance_proposals (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  inclusions text not null,
  current_price numeric not null default 0,
  standard_cost numeric not null default 0,
  standard_hours numeric not null default 0,
  valid_from date not null default current_date,
  is_demo boolean not null default false,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists finance_events (
  id uuid primary key default gen_random_uuid(),
  external_event_id text,
  client_name text not null,
  event_date date not null,
  proposal_id uuid references finance_proposals(id),
  list_price numeric not null default 0,
  discount numeric not null default 0,
  extras numeric not null default 0,
  payment_method text,
  payment_fee_rate numeric not null default 0,
  tax_rate numeric not null default 0,
  estimated_cost numeric not null default 0,
  actual_cost numeric,
  actual_hours numeric,
  kilometers numeric not null default 0,
  status text not null default 'cotizado',
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_finance_events_date on finance_events(event_date);
create index if not exists idx_finance_events_proposal on finance_events(proposal_id);

create table if not exists finance_event_costs (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references finance_events(id) on delete cascade,
  category text not null,
  item_name text not null,
  stage text,
  quantity numeric not null default 0,
  unit text,
  unit_cost numeric not null default 0,
  cost_date date not null default current_date,
  is_standard boolean not null default false,
  notes text
);

create index if not exists idx_finance_event_costs_event on finance_event_costs(event_id);

create table if not exists finance_people (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text not null,
  hourly_rate numeric not null default 0,
  monthly_salary numeric not null default 0,
  is_partner boolean not null default false,
  active boolean not null default true
);

create table if not exists finance_event_hours (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references finance_events(id) on delete cascade,
  person_id uuid not null references finance_people(id),
  stage text not null,
  hours numeric not null check (hours >= 0),
  hourly_rate numeric not null check (hourly_rate >= 0),
  work_date date
);

create index if not exists idx_finance_hours_event on finance_event_hours(event_id);

create table if not exists finance_assets (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text,
  purchase_value numeric not null default 0,
  purchase_date date,
  useful_events numeric,
  useful_months numeric,
  quantity numeric not null default 1,
  state text,
  replacement_value numeric,
  active boolean not null default true
);

create table if not exists finance_asset_uses (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references finance_events(id) on delete cascade,
  asset_id uuid not null references finance_assets(id),
  quantity numeric not null default 1,
  cost_per_use numeric not null default 0,
  damage_cost numeric not null default 0,
  notes text
);

create table if not exists finance_cash_movements (
  id uuid primary key default gen_random_uuid(),
  movement_date date not null,
  due_date date,
  event_id uuid references finance_events(id),
  movement_type text not null check (movement_type in ('income','expense')),
  category text not null,
  description text,
  amount numeric not null check (amount >= 0),
  paid boolean not null default true,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_finance_cash_date on finance_cash_movements(movement_date);
create index if not exists idx_finance_cash_due on finance_cash_movements(due_date) where paid = false;

create table if not exists finance_monthly_budget (
  id uuid primary key default gen_random_uuid(),
  month date not null,
  category text not null,
  budget_amount numeric not null default 0,
  driver text,
  notes text,
  unique(month, category)
);

create table if not exists finance_advertising (
  id uuid primary key default gen_random_uuid(),
  month date not null,
  campaign text,
  spend numeric not null default 0,
  leads integer not null default 0,
  inquiries integer not null default 0,
  bookings integer not null default 0,
  attributed_revenue numeric not null default 0
);

create table if not exists finance_audit_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  changed_by text,
  before_data jsonb,
  after_data jsonb,
  changed_at timestamptz not null default now()
);
